# Generated by Django 4.2.4 on 2025-01-22 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_ptwform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PTWForm',
        ),
    ]
