# Generated by Django 4.2.4 on 2025-01-22 08:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_delete_ptwform'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalSafety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SafetyPrecaution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='WorkLocationIsolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PTWForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('work_description', models.TextField()),
                ('equipment_tools_materials', models.TextField()),
                ('risk_assessment_done', models.BooleanField(default=False)),
                ('start_datetime', models.DateTimeField()),
                ('duration', models.CharField(max_length=255)),
                ('days', models.IntegerField()),
                ('workers_count', models.IntegerField()),
                ('department', models.CharField(max_length=255)),
                ('contractor', models.CharField(max_length=255)),
                ('contractor_supervisor', models.CharField(max_length=255)),
                ('additional_precautions', models.TextField(blank=True)),
                ('supervisor_name', models.CharField(max_length=255)),
                ('applicant_name', models.CharField(max_length=255)),
                ('applicant_date', models.DateField()),
                ('applicant_sign', models.CharField(max_length=255)),
                ('facility_manager_name', models.CharField(max_length=255)),
                ('facility_manager_date', models.DateField()),
                ('facility_manager_sign', models.CharField(max_length=255)),
                ('certificates_required', models.TextField()),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField()),
                ('initials', models.CharField(max_length=100)),
                ('contractor_name', models.CharField(max_length=255)),
                ('contractor_date', models.DateField()),
                ('contractor_sign', models.CharField(max_length=255)),
                ('hseq_name', models.CharField(max_length=255)),
                ('hseq_date', models.DateField()),
                ('hseq_sign', models.CharField(max_length=255)),
                ('work_acceptance_name', models.CharField(max_length=255)),
                ('work_acceptance_date', models.DateField()),
                ('work_acceptance_sign', models.CharField(max_length=255)),
                ('handover_status', models.CharField(max_length=255)),
                ('job_completion_reason', models.TextField(blank=True)),
                ('handover_name', models.CharField(max_length=255)),
                ('handover_date', models.DateField()),
                ('handover_sign', models.CharField(max_length=255)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('permit_applicant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('personal_safety', models.ManyToManyField(blank=True, to='app.personalsafety')),
                ('work_location_isolation', models.ManyToManyField(blank=True, to='app.worklocationisolation')),
                ('work_place', models.ManyToManyField(blank=True, to='app.safetyprecaution')),
            ],
        ),
    ]
