# Generated by Django 4.2.4 on 2025-01-22 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_personalsafety_safetyprecaution_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ptwform',
            name='permit_applicant',
        ),
        migrations.RemoveField(
            model_name='ptwform',
            name='personal_safety',
        ),
        migrations.RemoveField(
            model_name='ptwform',
            name='work_location_isolation',
        ),
        migrations.RemoveField(
            model_name='ptwform',
            name='work_place',
        ),
        migrations.DeleteModel(
            name='PersonalSafety',
        ),
        migrations.DeleteModel(
            name='PTWForm',
        ),
        migrations.DeleteModel(
            name='SafetyPrecaution',
        ),
        migrations.DeleteModel(
            name='WorkLocationIsolation',
        ),
    ]
