# Generated by Django 4.2.4 on 2025-01-22 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_ptwform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractor',
            name='work_detail',
        ),
        migrations.RemoveField(
            model_name='facilitymanager',
            name='certificates_required',
        ),
        migrations.RemoveField(
            model_name='facilitymanager',
            name='work_detail',
        ),
        migrations.RemoveField(
            model_name='hseq',
            name='work_detail',
        ),
        migrations.RemoveField(
            model_name='permitapplicant',
            name='work_detail',
        ),
        migrations.RemoveField(
            model_name='safetyprecaution',
            name='work_detail',
        ),
        migrations.RemoveField(
            model_name='validityandrenewal',
            name='work_detail',
        ),
        migrations.RemoveField(
            model_name='workdurationandpersonnel',
            name='work_detail',
        ),
        migrations.DeleteModel(
            name='Certificate',
        ),
        migrations.DeleteModel(
            name='Contractor',
        ),
        migrations.DeleteModel(
            name='FacilityManager',
        ),
        migrations.DeleteModel(
            name='HSEQ',
        ),
        migrations.DeleteModel(
            name='PermitApplicant',
        ),
        migrations.DeleteModel(
            name='SafetyPrecaution',
        ),
        migrations.DeleteModel(
            name='ValidityAndRenewal',
        ),
        migrations.DeleteModel(
            name='WorkDetail',
        ),
        migrations.DeleteModel(
            name='WorkDurationAndPersonnel',
        ),
    ]
