# Generated by Django 4.2.4 on 2025-01-22 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_ptwform_equipment_tools_materials_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ptwform',
            name='contractor',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ptwform',
            name='contractor_supervisor',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ptwform',
            name='days',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ptwform',
            name='department',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ptwform',
            name='duration',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ptwform',
            name='start_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='ptwform',
            name='workers_count',
            field=models.IntegerField(null=True),
        ),
    ]
