# Generated by Django 4.2.4 on 2025-01-22 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_ptwform_contractor_ptwform_contractor_supervisor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalSafety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SafetyPrecaution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='WorkLocationIsolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='ptwform',
            name='additional_precautions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ptwform',
            name='applicant_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='ptwform',
            name='applicant_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ptwform',
            name='applicant_sign',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ptwform',
            name='certificates_required',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='ptwform',
            name='contractor_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='ptwform',
            name='contractor_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ptwform',
            name='contractor_sign',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ptwform',
            name='facility_manager_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='ptwform',
            name='facility_manager_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ptwform',
            name='facility_manager_sign',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ptwform',
            name='hseq_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='ptwform',
            name='hseq_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ptwform',
            name='hseq_sign',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ptwform',
            name='initials',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ptwform',
            name='supervisor_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ptwform',
            name='valid_from',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='ptwform',
            name='valid_to',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='ptwform',
            name='personal_safety',
            field=models.ManyToManyField(blank=True, to='app.personalsafety'),
        ),
        migrations.AddField(
            model_name='ptwform',
            name='work_location_isolation',
            field=models.ManyToManyField(blank=True, to='app.worklocationisolation'),
        ),
        migrations.AddField(
            model_name='ptwform',
            name='work_place',
            field=models.ManyToManyField(blank=True, to='app.safetyprecaution'),
        ),
    ]
