# Generated by Django 4.2.4 on 2025-01-22 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_personalsafety_safetyprecaution_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ptwform',
            name='applicant_date',
        ),
        migrations.RemoveField(
            model_name='ptwform',
            name='applicant_name',
        ),
        migrations.RemoveField(
            model_name='ptwform',
            name='applicant_sign',
        ),
        migrations.RemoveField(
            model_name='ptwform',
            name='certificates_required',
        ),
        migrations.RemoveField(
            model_name='ptwform',
            name='contractor_date',
        ),
        migrations.RemoveField(
            model_name='ptwform',
            name='contractor_name',
        ),
        migrations.RemoveField(
            model_name='ptwform',
            name='contractor_sign',
        ),
        migrations.RemoveField(
            model_name='ptwform',
            name='facility_manager_date',
        ),
        migrations.RemoveField(
            model_name='ptwform',
            name='facility_manager_name',
        ),
        migrations.RemoveField(
            model_name='ptwform',
            name='facility_manager_sign',
        ),
        migrations.RemoveField(
            model_name='ptwform',
            name='hseq_date',
        ),
        migrations.RemoveField(
            model_name='ptwform',
            name='hseq_name',
        ),
        migrations.RemoveField(
            model_name='ptwform',
            name='hseq_sign',
        ),
        migrations.RemoveField(
            model_name='ptwform',
            name='initials',
        ),
        migrations.RemoveField(
            model_name='ptwform',
            name='supervisor_name',
        ),
        migrations.RemoveField(
            model_name='ptwform',
            name='valid_from',
        ),
        migrations.RemoveField(
            model_name='ptwform',
            name='valid_to',
        ),
    ]
