# Generated by Django 4.2.4 on 2025-01-22 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_ptwform_certificates_required_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ptwform',
            name='contractor_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='ptwform',
            name='contractor_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ptwform',
            name='contractor_sign',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ptwform',
            name='hseq_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='ptwform',
            name='hseq_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ptwform',
            name='hseq_sign',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ptwform',
            name='initials',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ptwform',
            name='valid_from',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='ptwform',
            name='valid_to',
            field=models.DateField(null=True),
        ),
    ]
