# Generated by Django 4.2.4 on 2025-01-25 23:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0016_ptwform_contractor_date_ptwform_contractor_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hazards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='NHISForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('date', models.DateField(null=True)),
                ('question', models.CharField(choices=[('option1', 'Option 1'), ('option2', 'Option 2')], max_length=7, null=True)),
                ('risk_type', models.CharField(blank=True, choices=[('UA', 'UA (Unsafe Act)'), ('UC', 'UC (Unsafe Condition)'), ('NM', 'NM (Near Miss)')], max_length=255, null=True)),
                ('ram_rating', models.CharField(blank=True, choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=255, null=True)),
                ('observation', models.TextField(blank=True)),
                ('action_taken', models.TextField(blank=True)),
                ('preventive_action', models.TextField(blank=True)),
                ('responsible_party', models.CharField(max_length=255, null=True)),
                ('target_date', models.DateField(null=True)),
                ('observed_by', models.CharField(max_length=255, null=True)),
                ('dept', models.CharField(max_length=255, null=True)),
                ('observed_date', models.DateField(null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=6)),
                ('hazard', models.ManyToManyField(blank=True, to='app.hazards')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
