# Generated by Django 4.2.4 on 2025-01-26 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_hazards_nhisform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nhisform',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('awaiting_supervisor', 'Awaiting Supervisor Approval'), ('awaiting_manager', 'Awaiting Manager Approval'), ('closed', 'Closed')], default='open', max_length=20),
        ),
    ]
