# Generated by Django 4.2.4 on 2025-01-27 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_nhisform_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nhisform',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('awaiting_supervisor', 'Awaiting Supervisor Approval'), ('awaiting_manager', 'Awaiting Manager Approval'), ('closed', 'Closed'), ('denied', 'Denied')], default='open', max_length=20),
        ),
    ]
