# Generated by Django 4.2.4 on 2025-01-29 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_nhisform_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='nhisform',
            name='date_submitted',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='ptwform',
            name='date_submitted',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
