# Generated by Django 4.2.4 on 2025-01-30 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_nhisform_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nhisform',
            name='status',
            field=models.CharField(choices=[('awaiting_supervisor', 'Awaiting Supervisor Approval'), ('awaiting_manager', 'Awaiting Manager Approval'), ('closed', 'Closed'), ('denied', 'Denied')], default='awaiting_supervisor', max_length=20),
        ),
    ]
