# Generated by Django 4.2.4 on 2025-01-30 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_nhisform_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ptwform',
            name='manager_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='ptwform',
            name='manager_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ptwform',
            name='manager_sign',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ptwform',
            name='status',
            field=models.CharField(choices=[('awaiting_supervisor', 'Awaiting Supervisor Approval'), ('supervisor_signed', 'Supervisor Signed'), ('awaiting_manager', 'Awaiting Manager Approval'), ('manager_signed', 'Manager Signed'), ('approved', 'Approved'), ('disapproved', 'Disapproved')], default='awaiting_supervisor', max_length=20),
        ),
    ]
